# Results p. 1
## Sample-by-Sample Evaluation

In [1]:
import copy

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.io as pio

import peyes._utils.constants
from analysis._article_results.lund2013._helpers import *
import analysis.statistics.sample_metrics as sm

pio.renderers.default = "browser"

C:\Users\jonathanni\PycharmProjects\pEYES\venv\Lib\site-packages\statsmodels\tools\tools.py:6: UserWarning: A NumPy version >=1.23.5 and <2.3.0 is required for this version of SciPy (detected version 2.3.0)
  import scipy.linalg

### Load Data

In [2]:
global_measures = sm.load_global_metrics(DATASET_NAME, PROCESSED_DATA_DIR, stimulus_type=STIMULUS_TYPE, metric=None, iteration=1)
global_measures.drop(index=[peyes.constants.ACCURACY_STR, peyes.constants.BALANCED_ACCURACY_STR], inplace=True)    # Drop Acc+Balanced-Acc metrics

### Sample-by-Sample Comparison
Evaluate performance on the sample-by-sample level using metrics for all labels together:
- Cohen's $\kappa$
- MCC
- $1-NLD$

In [3]:
global_stats, global_pvalues, global_nemenyi, sm_global_Ns = sm.friedman_nemenyi(global_measures, [GT1, GT2])

global_pvalues <= ALPHA

gt                MN    RA
metric
cohen's_kappa   True  True
complement_nld  True  True
mcc             True  True

In [4]:
pd.concat([global_stats, global_pvalues], axis=1, keys=['Q', 'p']).stack(1, future_stack=True)

                           Q             p
metric         gt
cohen's_kappa  MN  61.600000  2.128058e-11
               RA  76.525561  1.861656e-14
complement_nld MN  58.575096  8.760943e-11
               RA  81.838275  1.489657e-15
mcc            MN  62.769231  1.229975e-11
               RA  80.152466  3.322933e-15

#### Post-Hoc Analysis
**Cohen's Kappa**

In [5]:
post_hoc_kappa = sm.post_hoc_table(global_nemenyi, peyes.constants.COHENS_KAPPA_STR, [GT1, GT2], alpha=ALPHA, marginal_alpha=MARGINAL_ALPHA)
post_hoc_kappa

pred            ivt    ivvt     idt    idvt engbert      nh remodnav
pred     gt
ivt      MN      --    n.s.     ***       *    n.s.    n.s.     n.s.
         RA      --    n.s.     ***      **    n.s.    n.s.     n.s.
ivvt     MN  1.0000      --      **       *    n.s.    n.s.     n.s.
         RA  1.0000      --     ***      **    n.s.    n.s.     n.s.
idt      MN  0.0006  0.0013      --    n.s.     ***    n.s.     n.s.
         RA  0.0003  0.0003      --    n.s.     ***       â€      n.s.
idvt     MN  0.0140  0.0259  0.9923      --      **    n.s.     n.s.
         RA  0.0052  0.0048  0.9969      --     ***    n.s.     n.s.
engbert  MN  0.9973  0.9894  0.0000  0.0010      --    n.s.        *
         RA  0.9855  0.9872  0.0000  0.0001      --    n.s.     n.s.
nh       MN  0.8163  0.8926  0.1225  0.5188  0.4215      --     n.s.
         RA  0.8914  0.8839  0.0519  0.2580  0.3880      --     n.s.
remodnav MN  0.1859  0.2683  0.7186  0.9832  0.0331  0.9553       --
         RA  0.7795  0.7685  0.1030  0.3974  0.2505  1.0000       --

In [6]:
post_hoc_mcc = sm.post_hoc_table(global_nemenyi, peyes.constants.MCC_STR, [GT1, GT2], alpha=ALPHA, marginal_alpha=MARGINAL_ALPHA)
post_hoc_mcc

pred            ivt    ivvt     idt    idvt engbert      nh remodnav
pred     gt
ivt      MN      --    n.s.     ***       *    n.s.    n.s.     n.s.
         RA      --    n.s.     ***      **    n.s.    n.s.     n.s.
ivvt     MN  0.9998      --      **       â€     n.s.    n.s.     n.s.
         RA  1.0000      --      **       *    n.s.    n.s.     n.s.
idt      MN  0.0005  0.0031      --    n.s.     ***    n.s.     n.s.
         RA  0.0003  0.0012      --    n.s.     ***    n.s.     n.s.
idvt     MN  0.0152  0.0562  0.9898      --      **    n.s.     n.s.
         RA  0.0094  0.0235  0.9927      --     ***    n.s.     n.s.
engbert  MN  0.9985  0.9729  0.0000  0.0015      --    n.s.        â€
         RA  0.9923  0.9656  0.0000  0.0003      --    n.s.     n.s.
nh       MN  0.7117  0.9047  0.1836  0.6582  0.3442      --     n.s.
         RA  0.6997  0.8385  0.1596  0.5864  0.2309      --     n.s.
remodnav MN  0.2342  0.4659  0.6398  0.9729  0.0562  0.9916       --
         RA  0.7399  0.8679  0.1361  0.5418  0.2640  1.0000       --

In [7]:
post_hoc_nld = sm.post_hoc_table(global_nemenyi, peyes.constants.COMPLEMENT_NLD_STR, [GT1, GT2], alpha=ALPHA, marginal_alpha=MARGINAL_ALPHA)
post_hoc_nld

pred            ivt    ivvt     idt    idvt engbert      nh remodnav
pred     gt
ivt      MN      --    n.s.    n.s.    n.s.    n.s.    n.s.        *
         RA      --    n.s.    n.s.    n.s.    n.s.    n.s.       **
ivvt     MN  0.9985      --    n.s.    n.s.    n.s.    n.s.        â€
         RA  0.9992      --    n.s.    n.s.    n.s.    n.s.        *
idt      MN  0.8511  0.9879      --    n.s.    n.s.    n.s.     n.s.
         RA  0.5094  0.8235      --    n.s.    n.s.    n.s.     n.s.
idvt     MN  0.9236  0.9973  1.0000      --    n.s.    n.s.     n.s.
         RA  0.6152  0.8914  1.0000      --    n.s.    n.s.     n.s.
engbert  MN  1.0000  0.9932  0.7602  0.8586      --    n.s.       **
         RA  1.0000  0.9931  0.3594  0.4596      --    n.s.       **
nh       MN  0.9904  1.0000  0.9979  0.9998  0.9721      --     n.s.
         RA  0.9543  0.9986  0.9823  0.9938  0.8864      --     n.s.
remodnav MN  0.0113  0.0726  0.4325  0.3130  0.0057  0.1324       --
         RA  0.0035  0.0243  0.6141  0.5083  0.0013  0.1269       --

### Joint Violin Figure

In [8]:
W, H = 600, 450

global_metrics_fig = sm.global_metrics_distributions_figure(
    global_measures,
    gt1=GT1,
    gt2=GT2,
    colors={k: v[1] for k, v in LABELER_PLOTTING_CONFIG.items()},
    only_box=False,
    show_other_gt=True,
    share_x=True,
)

global_metrics_fig.update_traces(width=0.95)     # make violins wider so there's less space between them
# Make "Other GT" violins double-sided
for t in global_metrics_fig.data:
    if t["legendgroup"] != "Other GT":
        continue
    t["visible"] = t["name"].split(',')[0] == GT1
    t["side"] = None

global_metrics_fig.update_layout(
    title=None,
    width=W, height=H,
    paper_bgcolor='rgba(0, 0, 0, 0)',
    plot_bgcolor='rgba(0, 0, 0, 0)',
    yaxis=dict(showgrid=False, zeroline=False, showline=False, range=[0, 1], tickfont=dict(size=14)),
    yaxis2=dict(showgrid=False, zeroline=False, showline=False, range=[0, 1], tickfont=dict(size=14)),
    yaxis3=dict(showgrid=False, zeroline=False, showline=False, range=[0, 1], tickfont=dict(size=14)),
    xaxis3=dict(showgrid=False, tickfont=dict(size=14), tickangle=0),
    margin=dict(l=10, r=10, b=10, t=10, pad=0),
    showlegend=False,
)
# global_metrics_fig.layout.annotations = []    # remove subtitles

# global_metrics_fig.show()

### Split Figure
Split the double-sided figure into two ridge-plots - one for each GT annotator

In [9]:
WIDTH, HEIGHT = 1000, 1000
ROW_TITLES = ["<b>Cohen's Kappa</b>", "<b>MCC</b>", "<b>1-<i>NLD</i></b>"]

FONT_FAMILY, FONT_COLOR = "Calibri", "black"
TITLE_FONT = dict(family=FONT_FAMILY, size=24, color=FONT_COLOR)
AXIS_LABEL_FONT = dict(family=FONT_FAMILY, size=20, color=FONT_COLOR)
AXIS_TICK_FONT = dict(family=FONT_FAMILY, size=18, color=FONT_COLOR)

In [10]:
def split_global_figure(global_fig: go.Figure, gt: str) -> go.Figure:
    gt2 = GT2 if gt == GT1 else GT1
    fig = make_subplots(
        rows=3, cols=1,
        shared_xaxes=True, shared_yaxes=False,
        row_titles=ROW_TITLES,
        vertical_spacing=0.025,
    )

    for trace in global_fig.data:
        if not trace['name'].startswith(gt):
            continue
        new_tr = copy.deepcopy(trace)

        # convert from violin plot to ridge plot by assigning the `y0` prop and removing `x0` prop
        if new_tr["x0"] == "Other GT":
            new_tr["y0"] = new_tr["name"] = new_tr["legendgroup"] = f"Ann. {gt2}"
        elif new_tr["x0"].startswith("i"):
            new_tr["y0"] = new_tr["name"] = new_tr["legendgroup"] = new_tr["x0"].replace("i", "I-").upper()
        elif new_tr["x0"] == "remodnav":
            new_tr["y0"] = new_tr["name"] = new_tr["legendgroup"] = "REMoDNaV"
        else:
            new_tr["y0"] = new_tr["name"] = new_tr["legendgroup"] = new_tr["x0"].upper()
        new_tr['x'] = new_tr['y']

        # reset irrelevant props
        new_tr['y'] = new_tr['x0'] = None
        new_tr["showlegend"] = new_tr['points'] = False
        new_tr["side"] = "positive"
        new_tr["box"] = None
        new_tr["meanline"] = dict(visible=True, width=3, color='lightgray')
        new_tr["width"] = 1.75
        new_tr["opacity"] = 1
        new_tr["visible"] = True

        # add the figure to correct subplot
        scalegroup = new_tr['scalegroup']
        r = 1 if scalegroup == "cohen's_kappa" else 2 if scalegroup == "mcc" else 3
        fig.add_trace(new_tr, row=r, col=1)

    fig.for_each_xaxis(lambda xax: xax.update(
        showline=False, zeroline=False, showgrid=False, gridcolor='lightgray', gridwidth=1, tickfont=AXIS_TICK_FONT,
    ))
    fig.for_each_yaxis(lambda yax: yax.update(
        title=dict(text="Detector", font=AXIS_LABEL_FONT, standoff=4),
        showline=False, zeroline=False, showgrid=True, gridcolor='lightgray', gridwidth=1, tickfont=AXIS_TICK_FONT,
    ))
    fig.for_each_annotation(lambda ann: ann.update(
        font=TITLE_FONT, textangle=0, xref='paper', xanchor='center', x=0.475,
        yref='paper', yanchor='top',
        y=1.02 if ann.text == ROW_TITLES[0] else 0.68 if ann.text == ROW_TITLES[1] else 0.33,
    ))

    fig.update_layout(
        font_family=FONT_FAMILY,
        width=WIDTH, height=HEIGHT,
        paper_bgcolor='rgba(0, 0, 0, 0)', plot_bgcolor='rgba(0, 0, 0, 0)',
        margin=dict(l=0, r=0, t=20, b=0, pad=0),
        showlegend=False,
    )
    return fig

#### RA Figure

In [11]:
NAME = "fig_2-RA"
ra_fig = split_global_figure(global_metrics_fig, "RA")

ra_fig.write_image(os.path.join(FIGURES_DIR, f"{NAME}.png"), scale=3)
ra_fig.write_json(os.path.join(FIGURES_DIR, f"{NAME}.json"))
ra_fig.show()

#### MN Figure

In [17]:
NAME = "supp_fig_D1-MN"
mn_fig = split_global_figure(global_metrics_fig, "MN")

mn_fig.write_image(os.path.join(FIGURES_DIR, f"{NAME}.png"), scale=3)
# mn_fig.write_json(os.path.join(FIGURES_DIR, f"{NAME}.json"))
mn_fig.show()

## Repeat Analysis
### Repeating the analysis with subset of image-stimulus trials that were recorded @ 500Hz

In [13]:
subset_global_measures = global_measures.drop(columns=NON_500HZ_TRIALS, level=peyes.constants.TRIAL_ID_STR)

sub_stats, sub_pvalues, sub_nemenyi, sub_Ns = sm.friedman_nemenyi(subset_global_measures, [GT1, GT2])
pd.concat([sub_stats, sub_pvalues, sub_pvalues <= ALPHA], axis=1, keys=['Q', 'p', 'is_sig']).stack(1, future_stack=True)

                           Q             p  is_sig
metric         gt
cohen's_kappa  MN  52.278027  1.639525e-09    True
               RA  58.662934  8.408807e-11    True
complement_nld MN  50.430493  3.853602e-09    True
               RA  64.439462  5.614411e-12    True
mcc            MN  53.677130  8.570044e-10    True
               RA  62.304591  1.529480e-11    True

In [14]:
sub_post_hoc_kappa = sm.post_hoc_table(
    sub_nemenyi, peyes.constants.COHENS_KAPPA_STR, [GT1, GT2], alpha=ALPHA, marginal_alpha=MARGINAL_ALPHA
)
sub_post_hoc_kappa

pred            ivt    ivvt     idt    idvt engbert      nh remodnav
pred     gt
ivt      MN      --    n.s.      **       *    n.s.    n.s.     n.s.
         RA      --    n.s.      **       *    n.s.    n.s.     n.s.
ivvt     MN  1.0000      --      **       â€     n.s.    n.s.     n.s.
         RA  1.0000      --      **       *    n.s.    n.s.     n.s.
idt      MN  0.0018  0.0050      --    n.s.     ***    n.s.     n.s.
         RA  0.0037  0.0053      --    n.s.     ***    n.s.     n.s.
idvt     MN  0.0323  0.0679  0.9928      --      **    n.s.     n.s.
         RA  0.0349  0.0455  0.9978      --      **    n.s.     n.s.
engbert  MN  0.9993  0.9932  0.0002  0.0052      --    n.s.     n.s.
         RA  0.9976  0.9952  0.0002  0.0036      --    n.s.     n.s.
nh       MN  0.7166  0.8466  0.3113  0.7844  0.3901      --     n.s.
         RA  0.7322  0.7799  0.3980  0.7837  0.3372      --     n.s.
remodnav MN  0.3093  0.4590  0.7187  0.9822  0.1017  0.9971       --
         RA  0.9412  0.9595  0.1519  0.4732  0.6541  0.9994       --

In [15]:
sub_post_hoc_mcc = sm.post_hoc_table(
    sub_nemenyi, peyes.constants.MCC_STR, [GT1, GT2], alpha=ALPHA, marginal_alpha=MARGINAL_ALPHA
)
sub_post_hoc_mcc

pred            ivt    ivvt     idt    idvt engbert      nh remodnav
pred     gt
ivt      MN      --    n.s.      **       *    n.s.    n.s.     n.s.
         RA      --    n.s.      **       â€     n.s.    n.s.     n.s.
ivvt     MN  0.9993      --       *    n.s.    n.s.    n.s.     n.s.
         RA  0.9999      --       *    n.s.    n.s.    n.s.     n.s.
idt      MN  0.0016  0.0125      --    n.s.     ***    n.s.     n.s.
         RA  0.0036  0.0134      --    n.s.     ***    n.s.     n.s.
idvt     MN  0.0370  0.1494  0.9888      --      **    n.s.     n.s.
         RA  0.0554  0.1373  0.9922      --      **    n.s.     n.s.
engbert  MN  0.9996  0.9759  0.0002  0.0077      --    n.s.     n.s.
         RA  0.9987  0.9824  0.0003  0.0083      --    n.s.     n.s.
nh       MN  0.6022  0.8798  0.4059  0.8867  0.3174      --     n.s.
         RA  0.5463  0.7592  0.5821  0.9504  0.2175      --     n.s.
remodnav MN  0.3508  0.6767  0.6607  0.9790  0.1407  0.9998       --
         RA  0.9568  0.9940  0.1253  0.5260  0.7349  0.9863       --

In [16]:
sub_post_hoc_nld = sm.post_hoc_table(
    sub_nemenyi, peyes.constants.COMPLEMENT_NLD_STR, [GT1, GT2], alpha=ALPHA, marginal_alpha=MARGINAL_ALPHA
)
sub_post_hoc_nld

pred            ivt    ivvt     idt    idvt engbert      nh remodnav
pred     gt
ivt      MN      --    n.s.    n.s.    n.s.    n.s.    n.s.        *
         RA      --    n.s.    n.s.    n.s.    n.s.    n.s.        â€
ivvt     MN  0.9984      --    n.s.    n.s.    n.s.    n.s.     n.s.
         RA  0.9989      --    n.s.    n.s.    n.s.    n.s.     n.s.
idt      MN  0.8784  0.9926      --    n.s.    n.s.    n.s.     n.s.
         RA  0.6466  0.9165      --    n.s.    n.s.    n.s.     n.s.
idvt     MN  0.9396  0.9985  1.0000      --    n.s.    n.s.     n.s.
         RA  0.7238  0.9494  1.0000      --    n.s.    n.s.     n.s.
engbert  MN  1.0000  0.9922  0.7901  0.8784      --    n.s.        *
         RA  1.0000  0.9952  0.5400  0.6222      --    n.s.        *
nh       MN  0.9893  1.0000  0.9991  0.9999  0.9681      --     n.s.
         RA  0.9283  0.9970  0.9983  0.9996  0.8732      --     n.s.
remodnav MN  0.0401  0.1866  0.6328  0.5064  0.0214  0.3013       --
         RA  0.0578  0.2239  0.9136  0.8684  0.0352  0.6146       --